# Generative Flow Networks (GFN) with Trajectory Balance (TB) loss
name: gfn_non_acyclic
step_size: ${target.gfn_non_acyclic.step_size}
bwd_step_size: ${target.gfn_non_acyclic.bwd_step_size}
batch_size: ${target.all.batch_size}
iters: ${target.all.iters}
num_steps: ${target.gfn_non_acyclic.num_steps}
grad_clip: ${target.gfn_non_acyclic.grad_clip}
weight_decay: ${target.gfn_non_acyclic.weight_decay}
loss_type: ${target.gfn_non_acyclic.loss_type}
n_chunks: ${target.gfn_non_acyclic.num_steps}
init_logZ: ${target.gfn_non_acyclic.init_logZ}
logZ_step_size: ${target.gfn_non_acyclic.logZ_step_size}
init_std: ${target.gfn_non_acyclic.init_std}  # for ou
logr_clip: ${target.gfn_non_acyclic.logr_clip}
huber_delta: ${target.gfn_non_acyclic.huber_delta}
reg_coef: ${target.gfn_non_acyclic.reg_coef}
eval_max_steps: ${target.gfn_non_acyclic.eval_max_steps}
use_weights: True
only_clf_reg: False

# Learning rate scheduler
lr_schedule:
  type: multistep  # multistep | cosine | constant
  milestones: ${target.all.milestones}  # iteration indices at which to decay
  gamma: 1.0  # multiply LR by gamma at each milestone

defaults:
  - model: non_acyclic_net

model:
  use_lp: ${target.all.use_lp}
  num_hid: ${target.all.num_hid}
  fwd_log_var_range: ${target.all.fwd_log_var_range}
  bwd_log_var_range: ${target.all.bwd_log_var_range}
  outer_clip: ${target.all.outer_clip}
  inner_clip: ${target.all.inner_clip}
  mean_clip: ${target.all.mean_clip}
  use_preconditioner: False

buffer:
  use: True
  max_length_in_batches: 100
  prioritize_by: "reward"  # none, reward, loss, uiw, piw
  target_ess: 0.05
  sampling_method: "systematic"  # multinomial, stratified, systematic, rank
  rank_k: 0.01  # only used if sampling_method is rank
  sample_with_replacement: True
  prefill_steps: 100  # collect `prefill_steps` batches before starting training
  bwd_to_fwd_ratio: 2  # number of bwd steps per fwd step
  update_score: False

local_search:
  use: True
  cycle: 25
  gamma: 1e-3
  num_steps: 300