dim: ${target.dim}

num_layers: 4
num_hid: 128
outer_clip: 1e4
inner_clip: 1e2

weight_init: 1e-8
bias_init: 0.1

gamma: ${target.gfn_non_acyclic.gamma}
num_levels: 2
learn_fwd: True
learn_bwd: True

fwd_log_var_range: 4
bwd_log_var_range: 4