name: funnel
dim: 10
has_entropy: False

fn:
  _target_: targets.funnel.Funnel
  dim: ${target.dim}
  log_Z: 0.
  can_sample: True
  sample_bounds: [-30, 30]

# Experiment-specific algorithm parameters
# ----------------------------------------

dis: # Time-reversed Diffusion Sampler
  init_std: 1.
  step_size: 5e-4

gbs:  # General Bridge Sampler
  max_diffusion: 1.
  init_std: 1.
  step_size: 5e-4

############# HYPERPARAMETERS USED IN OUR PAPER #############
# These can be slightly different from the original settings

pis: # Path Integral Sampler
  max_diffusion: 1.
  step_size: 1e-3

dds: # Denoising Diffusion Sampler
  init_std: 1.
  step_size: 1e-3

gfn_tb: # Trajectory Balance
  reference_process: ou_dds  # pinned_brownian, ou, or ou_dds
  init_std: 1.  # for ou or ou_dss
  max_diffusion: 1.  # for pinned_brownian or ou
  step_size: 1e-3
  logZ_step_size: 1e-1
  init_logZ: 0.

gfn_subtb: # Sub-Trajectory Balance
  reference_process: ou_dds  # pinned_brownian, ou, or ou_dds
  init_std: 1.  # for ou or ou_dds
  max_diffusion: 1.  # for pinned_brownian or ou
  n_chunks: 16
  step_size: 1e-3
  logflow_step_size: 1e-3
  beta_step_size: 1e-1
  logZ_step_size: 1e-1  # for ou or ou_dds
  init_logZ: 0.  # for ou or ou_dds
  mcmc_step_size: 0.2
  flow_num_hid: 64

gfn_non_acyclic:
  init_std: 1.0
  weight_decay: 0.0
  step_size: 1e-4
  bwd_step_size: 1e-4
  logZ_step_size: 1e-1
  init_logZ: 0.
  gamma: 0.1
  reg_coef: 1.0
  num_steps: 50
  eval_max_steps: 500
  loss_type: tb
  logr_clip: -1e5
  huber_delta: null
  grad_clip: 0.001

gfn_non_acyclic_ml:
  init_std: 1.0
  weight_decay: 0.0
  step_size: 1e-4
  bwd_step_size: 1e-4
  logZ_step_size: 1e-1
  init_logZ: 0.
  gamma: 0.1
  reg_coef: 1.0
  num_steps: 50
  eval_max_steps: 500
  loss_type: tb
  logr_clip: -1e5
  huber_delta: null
  grad_clip: 0.001
  num_levels: 2

all: # Parameters that are shared between all algorithms
  batch_size: 2000
  iters: 50000
  milestones: [10000, 20000, 30000, 40000]
  num_steps: 64
  use_lp: False
  num_hid: 128
  fwd_log_var_range: 2
  bwd_log_var_range: 2
  outer_clip: 2e1
  inner_clip: 1e1
  mean_clip: 10.0